package io.github.lucasbrovetto.financialintegration.transactionservice.adapters.outbound.persistence.mapper;

import io.github.lucasbrovetto.financialintegration.transactionservice.adapters.outbound.persistence.TransactionEntity;
import io.github.lucasbrovetto.financialintegration.transactionservice.domain.model.Transaction;
import org.mapstruct.Mapper;

/**
 * Persistence Mapper
 * Converts between the transaction domain aggregate and its JPA entity.
 */
@Mapper(componentModel = "spring")
public interface TransactionPersistenceMapper {

    /**
     * Convert a domain transaction to its persistence representation.
     * This implementation is generated by MapStruct at compile time.
     *
     * @param transaction domain transaction to persist
     * @return JPA entity with the transaction persistence fields
     */
    TransactionEntity toEntity(Transaction transaction);

    /**
     * Restore the immutable domain transaction from its persistence representation.
     * This method is implemented manually because the domain aggregate is created through
     * its restore factory method instead of a public constructor or setters.
     *
     * @param entity persisted transaction entity
     * @return restored domain transaction
     */
    default Transaction toDomain(TransactionEntity entity) {
        return Transaction.restore(
                entity.getId(),
                entity.getTerminalId(),
                entity.getAmount(),
                entity.getType(),
                entity.getStatus(),
                entity.getCreatedAt(),
                entity.getUpdatedAt(),
                entity.getFailureReason()
        );
    }
}
