spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/financial_platform}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${JPA_SHOW_SQL:false}
  flyway:
    baseline-on-migrate: true
