spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/financial_platform
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
        name: transaction-service
server:
    port: 8080